language: ruby
rvm:
- 2.0.0
- 1.9.3
env:
  global:
  - secure: oqsldFSn/mncyjQG6zgdeAJcKx54WeZVXmIl2sZ+GB+BVmzzT9l0jhs3vAfEp2Q66n0iVMsjyT86VOw4oZGKjuldMpZsop3IHOHrhgRYhp3le7eYzip2+ZIPN189Vpqj0E/GLiZDCOylVvrq3OZ4f/6MqGvGFoMHRnEE/BmwP4Y=
notifications:
  email: false
